# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: adessoAG DevBlog
email: test@test.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Hello, world!</h3><h1>DevJournal</h1><h3>Awesome Jekyll Theme for Developers!</h3>Hope you like it!"

# permalink
permalink: blog-posts/:year-:month-:day/:title.html

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true